# Generated by Django 6.0.3 on 2026-04-29 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='New conversation', max_length=255)),
                ('user_id', models.IntegerField(db_index=True)),
                ('user_email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('mode', models.CharField(choices=[('general', 'General'), ('incident', 'Incident'), ('rca', 'RCA'), ('email', 'Email'), ('monitoring', 'Monitoring'), ('map', 'Map')], db_index=True, default='general', max_length=20)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'assistant_conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], db_index=True, max_length=20)),
                ('mode', models.CharField(choices=[('general', 'General'), ('incident', 'Incident'), ('rca', 'RCA'), ('email', 'Email'), ('monitoring', 'Monitoring'), ('map', 'Map')], db_index=True, default='general', max_length=20)),
                ('content', models.TextField()),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('parsed_payload', models.JSONField(blank=True, default=dict)),
                ('model_name', models.CharField(blank=True, default='', max_length=255)),
                ('prompt_version', models.CharField(blank=True, default='v1', max_length=100)),
                ('is_training_candidate', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant_api.assistantconversation')),
            ],
            options={
                'db_table': 'assistant_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('user_email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('rating', models.SmallIntegerField(blank=True, null=True)),
                ('corrected_answer', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('use_for_finetuning', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_items', to='assistant_api.assistantmessage')),
            ],
            options={
                'db_table': 'assistant_feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
