# Generated by Django 6.0.3 on 2026-05-01 01:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_index=True)),
                ('user_email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('warning', 'Warning'), ('info', 'Info'), ('success', 'Success')], db_index=True, default='info', max_length=20)),
                ('source', models.CharField(choices=[('incident', 'Incident'), ('monitoring', 'Monitoring'), ('rca', 'RCA'), ('ai', 'AI'), ('email', 'Email'), ('system', 'System')], db_index=True, default='system', max_length=20)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read')], db_index=True, default='unread', max_length=20)),
                ('entity_label', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
