# Generated by Django 6.0.3 on 2026-04-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(default='imported_ticket', max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor'), ('warning', 'Warning')], default='major', max_length=20)),
                ('priority', models.CharField(blank=True, max_length=20, null=True)),
                ('problem_family', models.CharField(blank=True, max_length=150, null=True)),
                ('ticket_type', models.CharField(blank=True, max_length=150, null=True)),
                ('site_name', models.CharField(blank=True, max_length=150, null=True)),
                ('region_code', models.CharField(blank=True, max_length=20, null=True)),
                ('technology', models.CharField(default='3G', max_length=10)),
                ('assigned_team', models.CharField(blank=True, max_length=150, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('health_impact_score', models.FloatField(blank=True, null=True)),
                ('root_cause_hint', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'incident',
                'ordering': ['-started_at', '-created_at'],
            },
        ),
    ]
